# Enterprise Config Overrides

# Is this an enterprise (non http://algorithmia.com) site?
enterprise: true

# In enterprise installs the CDN won't be used, so just send requests
# back to the dev center Node server.
cdnurl: ""
