# Enterprise Config Overrides

# Is this an enterprise (non http://algorithmia.com) site?
enterprise: true

# Force all asset requests to be served locally for entrprise builds,
# to support customers without public internet access.
cdnurl: ""
